import { expoRecommend } from "./expo-recommend.js";
import { expoComponent } from "./expoComponent.js";
import { expoDiscoverComponent } from "./expoDiscoverComponent.js";
import { getData, getSearch, renderExpoComponent, renderRecommendComponent } from "./getData.js";
import { english, spanish } from "./homeDictionary.js";
import { exceptionTranslate, getLangArray, langComponent, placeHolderTranslate, startLang, translateLang } from "./langComponent.js";
import { menuComponent } from "./menuComponent.js";
import { searchComponent, searchLoadEvent } from "./searchComponent.js";
import { settingsHomeComponent } from "./settingsHomeComponent.js";

console.log("Importado !");

globalThis.expoRecommend = expoRecommend;
globalThis.expoComponent = expoComponent;
globalThis.getData = getData;
globalThis.getSearch = getSearch;
globalThis.renderExpoComponent = renderExpoComponent;
globalThis.renderRecommendComponent = renderRecommendComponent;
globalThis.menuComponent  = menuComponent;
globalThis.settingsHomeComponent  = settingsHomeComponent;
globalThis.langComponent = langComponent;
globalThis.startLang = startLang;
globalThis.placeHolderTranslate = placeHolderTranslate;
globalThis.exceptionTranslate = exceptionTranslate;
globalThis.translateLang = translateLang;
globalThis.getLangArray =  getLangArray;
globalThis.english = english;
globalThis.spanish = spanish;
globalThis.expoDiscoverComponent = expoDiscoverComponent;
globalThis.searchComponent = searchComponent;
globalThis.searchLoadEvent = searchLoadEvent;